### ISSUE TITLE
Please update the file submitted to Luogu

### ISSUE THREAD

**Issue by Lounode** [YanWQ-monad/SmojSubmit#2]
请先参阅 [Bug 反馈](https://github.com/YanWQ-monad/SmojSubmit/wiki/Bug)

### 基本信息
- Sublime Text 版本：3.2.1
- 目标 OJ：luogu
- 题号：1001
- 目标 OJ 评测的 ID：null
- 期望行为：success
- 异常行为：can't submit 

### Sublime 日志
```
I..can't find it...
```

### 提交的代码
```
// P1001.cpp
#include <bits/stdc++.h>

int main ()
{
	int a,b;
	scanf("%d%d",&a,&b);
	printf("%d",a+b);
	return 0;
}
```

**Comment by YanWQ-monad** [comment]
应该好了（吧）
